name: endless randomness
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ea61e5e6-4cec-4fc4-ab79-9c63678a574a.jpg
layout_spectrum: 0.11061064633070537
typography_spectrum: 0.7610486538360578
analytics:
  twitter: '@mdnzero'
opengraph:
  type: ''
  appId: '1102225679823534'
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.7895404463700286
  lightness: 0.5085780318886374
  saturation: 0.9556485610686721
  rhythmicContrast: 0.28191507417256806
purpose:
  - type: external
    label: home
    url: 'http://pilido.com'
title: 'Photo, Life, Domains'
description: The never ending randomness and cats
author:
  name: mdno jx
content_rating:
  adult: false
navigation:
  - name: Gallery
    id: ceeec230-fb7c-4bda-936c-85f4537bdbd8
    type: content
  - name: Cats
    id: 62267dc6-61e6-4354-b0d9-19935de1cb02
    type: content
  - name: Photo Contest
    id: 567f2e79-b9c6-4258-b2c3-bc728b63cae9
    type: content
content: []
github: true
