layout_spectrum: 0.928606629164908
typography_spectrum: 0.05056402685148365
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.17895519774075194
  lightness: 0.5095796808623478
  saturation: 0.9571182101711372
  rhythmicContrast: 0.2801106904612135
name: endless randomness
favicon: null
analytics:
  twitter: '@mdnzero'
opengraph:
  type: ''
  appId: '1102225679823534'
purpose:
  - type: external
    label: home
    url: 'http://pilido.com'
title: 'Pitures, Life, Dominance'
description: The never ending randomness and cats
author:
  name: mdno jx
content_rating:
  adult: false
navigation:
  - name: Cats
    id: 62267dc6-61e6-4354-b0d9-19935de1cb02
    type: content
  - name: Photo Contest
    id: 567f2e79-b9c6-4258-b2c3-bc728b63cae9
    type: content
content: []
github: true
